url: "http://lisandroct.com"
baseurl: ""

collections: 
  blog-tags: 
    output: true
    permalink: /blog/tags/:name/

defaults: 
  - scope: 
      path: ""
      type: blog-tags
    values: 
      color: "108, 117, 147"
      layout: blog-tag
  - scope: 
      path: "_posts/blog"
    values: 
      category: blog
      layout: blog-post
      published: true
  - scope: 
      path: "_posts/portfolio"
    values: 
      category: portfolio
      published: true
  - scope: 
      path: "_posts/projects"
    values: 
      category: projects
      published: true

excerpt_separator: "<!-- more -->"

exclude: 
  - README.md

staticman_url: https://api.staticman.net/v2/entry/lisandroct/lisandroct.github.io/master/comments