url: "http://lisandroct.com"
baseurl: ""
exclude: ['README.md']

excerpt_separator: <!--more-->

collections:
  blog-tags:
    permalink: /blog/tags/:name/
    output: true

defaults:
  - scope:
      path: ""
      type: blog-tags
    values:
      layout: blog-tag
      color: "108, 117, 147"
      
repository: "lisandroCT/lisandroct.github.io"
      
# Staticman comments (full configuration in staticman.yml)
staticman:
  branch: "master"